apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: genai-ingress
  namespace: genai-assistant
spec:
  rules:
    - host: genai-assistant.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 8501
